# Generated by Django 5.2.7 on 2025-11-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillmate', '0002_device_medicinelog_dailydose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='is_taken_today',
        ),
    ]
